name: Workflow for PRs
on:
  pull_request:
    branches:
      - main

jobs:
  dispatch_workflow:
    runs-on: ubuntu-latest
    steps:
      - env:
          PAT: ${{ secrets.BOT_PAT }}
        run: |
          curl \
          -X POST \
          -H "Accept: application/vnd.github.v3+json"  \
          -H "Authorization: token ${PAT}"  \
          https://api.github.com/repos/looshlee/ideal-system/actions/workflows/wf_dispatch.yml/dispatches \
          -d '{"ref":"ref"}'
